{{- $root := . -}}
{{- if .Values.workers -}}
{{- range .Values.workers }}
{{- include "common.rolloutdeployment" (merge (deepCopy $root) (dict "service" . "type" "worker")) }}
---
{{- end -}}
{{- end -}}
