build:
  - changed-files:
      - any-glob-to-any-file:
          - Makefile
          - "**/tsconfig.*"
          - tsconfig.*

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/*
          - .github/workflows/**/*

deps:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum
          - package.json
          - package-lock.json

deployment:
  - changed-files:
      - any-glob-to-any-file:
          - .dockerignore
          - Containerfile
          - Dockerfile
          - plconfig.yaml

docs:
  - changed-files:
      - any-glob-to-any-file:
          - CODEOWNERS
          - "*.md"
          - "**/*.md"

json:
  - changed-files:
      - any-glob-to-any-file:
          - "*.json"
          - "**/*.json"

shell:
  - changed-files:
      - any-glob-to-any-file:
          - "*.sh"
          - "**/*.sh"

style:
  - changed-files:
      - any-glob-to-any-file:
          - .eslintignore
          - .eslintrc.js
          - .prettierignore
          - .prettierrc.json

test:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.spec.js"
          - "**/*.spec.ts"
          - "**/*.test.js"
          - "**/*.test.ts"
          - "**/__test__/*"
          - "**/__test__/**/*"

yaml:
  - changed-files:
      - any-glob-to-any-file:
          - "*.yaml"
          - "*.yml"
          - "**/*.yaml"
          - "**/*.yml"
