apiVersion: v2
name: cronjob
description: Single cron job
version: 0.0.68
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.2.5
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 19.6.4
    condition: redis.enabled
