apiVersion: v2
name: cronjob
description: Single cron job
version: 0.0.35
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.12.10
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.1.5
    condition: redis.enabled
