apiVersion: v2
name: cronjob
description: Single cron job
version: 0.4.0
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.7.27
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 22.0.7
    condition: redis.enabled
