apiVersion: v2
name: cronjob
description: Single cron job
version: 0.0.33
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.7.1
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.17.1
    condition: redis.enabled
