apiVersion: v2
name: cronjob
description: Single cron job
version: 0.0.91
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.38
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.5.0
    condition: redis.enabled
