apiVersion: v2
name: microservice
description: Simple microservice
version: 0.0.23
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.6.9
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.13.2
    condition: redis.enabled
