apiVersion: v2
name: microservice
description: Simple microservice
version: 0.0.49
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.2.5
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.7.1
    condition: redis.enabled
