apiVersion: v2
name: microservice
description: Simple microservice
version: 0.0.53
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.4.4
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.19.4
    condition: redis.enabled
