apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.0.25
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.2.2
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.8.4
    condition: redis.enabled
