apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.0.58
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.9
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.3.2
    condition: redis.enabled
