apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.0.83
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.21
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.19.4
    condition: redis.enabled
  - name: mongodb
    version: 15.6.19
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
