apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.1.12
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.38
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.11.5
    condition: redis.enabled
  - name: mongodb
    version: 16.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
