apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.6.0
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 22.0.7
    condition: redis.enabled
