apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.0.64
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.4.4
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.7.1
    condition: redis.enabled
