apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.0.74
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.2.5
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 19.6.4
    condition: redis.enabled
