apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.0.31
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.7.1
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.1.5
    condition: redis.enabled
