apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.0.26
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.5.6
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.11.3
    condition: redis.enabled
