apiVersion: v2
name: monolith
description: Application that may define multiple services and cronjobs
version: 0.2.0
dependencies:
  - name: common
    version: "*"
    repository: file://../common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 17.0.0
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 23.0.2
    condition: redis.enabled
  - name: mongodb
    version: 16.5.11
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
