{{- $root := . -}}
{{- if .Values.workers -}}
{{- range .Values.workers }}
{{- include "common.deployment" (merge (merge (deepCopy $root) (dict "worker" .)) (dict "service" . "type" "worker")) }}
---
{{- end -}}
{{- end -}}
