{{- $root := . -}}
{{- if .Values.extraServices -}}
{{- range .Values.extraServices }}
{{- include "common.deployment" (merge (deepCopy $root) (dict "service" . "type" "service")) }}
---
{{- end -}}
{{- end -}}
