{{- $root := . -}}
{{- $defaultWorker := .Values.worker}}
{{- if .Values.workers -}}
{{- range .Values.workers }}
{{- include "common.deployment" (merge (deepCopy $root) (dict "service" (mergeOverwrite (deepCopy $defaultWorker) .) "type" "worker")) }}
---
{{- end -}}
{{- end -}}
