name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yaml
      - parcellab/**
      - "!**.md"
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.generate-matrix.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load repos configuration file
        id: generate-matrix
        run: |
          export CHARTS=$(ls -d parcellab/* | awk ' BEGIN { ORS = ""; print "["; } { print "\/\@"$0"\/\@"; } END { print "]"; }' | sed "s^\"^\\\\\"^g;s^\/\@\/\@^\", \"^g;s^\/\@^\"^g")
          echo "::set-output name=charts::$CHARTS"
  test:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.matrix.outputs.charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update dependencies
        run: helm dependency update ${{ matrix.chart }}
      - name: Lint chart
        run: helm lint ${{ matrix.chart }}
      - name: Template chart
        run: |
          helm show chart ${{ matrix.chart }} | grep "type: library" || helm template ${{ matrix.chart }} > output.yaml
      - if: matrix.chart != 'parcellab/common'
        name: Evaluate k8s resources
        uses: instrumenta/kubeval-action@master
        with:
          files: output.yaml
  release:
    if: github.ref == 'refs/heads/main'
    needs: [test, matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.matrix.outputs.charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Check if chart has been updated
        id: chart_updated
        run: |
          CHART_PATH=${{ matrix.chart }}
          LAST_COMMIT=$(git log -1 --format=format:%H --full-diff $CHART_PATH)
          if [ "$(git rev-parse HEAD)" == "$LAST_COMMIT" ]; then
            echo "Chart has not been updated since the last commit."
            echo "::set-output name=updated::false"
          else
            echo "Chart has been updated."
            echo "::set-output name=updated::true"
          fi
      - name: Run chart-releaser
        if: steps.chart_updated.outputs.updated == 'true'
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ${{ matrix.chart }}
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
