name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yaml
      - parcellab/**
      - "!**.md"
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.generate-matrix.outputs.charts }}
      changed_charts: ${{ steps.changed-charts.outputs.list }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load repos configuration file
        id: generate-matrix
        run: |
          export CHARTS=$(ls -d parcellab/* | awk ' BEGIN { ORS = ""; print "["; } { print "\/\@"$0"\/\@"; } END { print "]"; }' | sed "s^\"^\\\\\"^g;s^\/\@\/\@^\", \"^g;s^\/\@^\"^g")
          echo "::set-output name=charts::$CHARTS"
      - name: Determine changed charts
        id: changed-charts
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- parcellab/ | grep -E 'parcellab/.*/' | awk -F '/' '{print $1"/"$2}' | uniq)
          CHANGED_JSON=$(echo $CHANGED | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=list::$CHANGED_JSON"
  test:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.matrix.outputs.changed_charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update dependencies
        run: helm dependency update ${{ matrix.chart }}
      - name: Lint chart
        run: helm lint ${{ matrix.chart }}
      - name: Template chart
        run: |
          helm show chart ${{ matrix.chart }} | grep "type: library" || helm template ${{ matrix.chart }} > output.yaml
      - if: matrix.chart != 'parcellab/common'
        name: Evaluate k8s resources
        uses: instrumenta/kubeval-action@master
        with:
          files: output.yaml
  release:
    if: github.ref == 'refs/heads/main'
    needs: [test, matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{fromJson(needs.matrix.outputs.changed_charts)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser for changed charts
        if: contains(matrix.include, matrix.chart)
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ${{ matrix.chart }}
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
